### ISSUE TITLE
react-dropdown Supporting RTL ?

### ISSUE THREAD

**Issue by kamaldlk** [trendmicro-frontend/react-dropdown#9]
react-dropdown Supporting RTL ?

**Comment by kamaldlk** [comment]
Hi any update on this

**Comment by cheton** [comment]
Hi @kamaldlk,

Sorry for that we don't have plan to support RTL in the near future since we don't have RTL experiences and development resources on that. However, you can modify the CSS file or use styled-components to extend Dropdown component to enable RTL support.

PR is welcome if you have anything that can contribute to this repo. Thank you.
